NAME = a.out

all: $(NAME)

	gcc -Wall -Werror -Wextra -o $^	ft_print.c	ft_itoa_base_len.c	../ft_strlen.c	../ft_strnew.c	../ft_bzero.c	../ft_putstr.c	-I../includes
		../ft_memset.c


clean:
	rm -rf $(NAME)